config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  devise_for :users
  resources :users do
    resources :questions
  end
  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users
    resources :exams
  end
  resources :exams

end

app/models/question.rb
class Question < ActiveRecord::Base
  resourcify
  enum status: [:waitting, :accepted]
  enum question_type: [:single, :multiple, :text]

  has_many :options, dependent: :destroy
  has_many :sections
  has_many :exams, through: :sections
  belongs_to :user
  belongs_to :subject

  accepts_nested_attributes_for :options,
    reject_if: proc{|attributes| attributes["content"].blank?},
    allow_destroy: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource

  before_action :load_subjects, except: [:index, :destroy]

  def index
    @q = Question.ransack params[:q]
    option = params[:option].nil? ? Settings.question.filter.all : params[:option]
    @questions = @q.result.includes(:subject).send(option).page(params[:page])
      .per Settings.pagination.questions_per_page
  end

  def create
    @question.user_id = current_user.id
    @question.status = Question.statuses[:accepted]
    if @question.save
      flash[:notice] = I18n.t "questions.created"
      redirect_to admin_questions_path
    else
      flash[:alert] = I18n.t "questions.create_fail"
      render :new
    end
  end

  def update
    if @question.update_attributes question_params
      flash[:notice] = I18n.t "questions.updated"
      redirect_to admin_questions_path
    else
      flash[:alert] = I18n.t "questions.update_fail"
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:notice] = I18n.t "questions.destroyed"
    redirect_to admin_questions_path
  end

  private

  def question_params
    params.require(:question).permit(:subject_id, :question_type, :content, :status,
      options_attributes: [:id, :content, :is_correct, :_destroy])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :load_subjects, except: [:index, :destroy]

  def index
    @user = User.friendly.find(params[:user_id])
    @questions = @user.questions.order("content")
      .page(params[:page]).per(5)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = I18n.t "questions.created"
      redirect_to user_questions_path current_user
    else
      flash[:alert] = I18n.t "questions.create_fail"
      render :new
    end
  end

  def show
    @question = Question.find params[:id]
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
    @question = Question.find params[:id]
    if @question.update_attributes question_params
      flash[:notice] = I18n.t "questions.updated"
      redirect_to user_questions_path
    else
      flash[:alert] = I18n.t "questions.update_fail"
      render :edit
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to user_questions_path(current_user)
    flash[:notice] = I18n.t "questions.destroyed"
  end

  private

  def question_params
    params.require(:question).permit(:subject_id, :question_type, :content,
      options_attributes: [:id, :content, :is_correct, :_destroy])
  end

end

app/views/admin/questions/_filter_as_status.html.erb
<div class="navbar-form navbar-left">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= t("questions.state") %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to  t("questions.statuses.all"),
        admin_questions_path(option: :all) %></li>
      <li><%= link_to  t("questions.statuses.accepted"),
        admin_questions_path(option: :accepted) %></li>
      <li><%= link_to  t("questions.statuses.waitting"),
        admin_questions_path(option: :waitting) %></li>
    </ul>
  </div>
</div>

app/views/admin/questions/_filter_as_type.html.erb
<div class="navbar-form navbar-left">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= t("questions.type") %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to  t("questions.types.all"),
        admin_questions_path(option: :all) %></li>
      <li><%= link_to  t("questions.types.single"),
        admin_questions_path(option: :single) %></li>
      <li><%= link_to  t("questions.types.multiple"),
        admin_questions_path(option: :multiple) %></li>
      <li><%= link_to  t("questions.types.text"),
        admin_questions_path(option: :text) %></li>
    </ul>
  </div>
</div>

app/views/admin/questions/_filter_question_options.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <div class="navbar-form navbar-left">
        <%= search_form_for [:admin, @q] do |f| %>
          <div class="form-group">
            <%= f.search_field :content_or_subject_name_cont,
              class: "form-control", placeholder: t("questions.placeholder") %>
          </div>
          <%= f.submit t("questions.search"), class: "btn btn-default" %>
        <% end %>
      </div>
      <%= render partial: "filter_as_type" %>
      <%= render partial: "filter_as_status" %>
    </div>
  </div>
</nav>

app/views/admin/questions/_option_fields.html.erb
<div class="fields form-group row">
  <p>
    <%= f.hidden_field :_destroy %>
    <%= f.label :content %>
    <div class="col-md-8">
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="col-md-4 correct-select">
      <%= f.check_box :is_correct, class: "correct-option" %>
      <span><%= t "questions.correct_option" %></span>
      <button class="delete_fields btn btn-danger">
        <%= t "questions.remove_option" %>
      </button>
    </div>
  </p>
</div>

app/views/admin/questions/edit.html.erb
<div id="question" class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t "questions.suggest_question" %></b></h2>
    <%= form_for [:admin, @question] do |f| %>
      <div class="row">
        <%= f.label :subject %>
        <%= f.select :subject_id,
          options_for_select(@subjects.collect{|subject| [subject.name, subject.id]},
          @question.subject.id), {}, {class: "form-control"} %>
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
        <%= f.label :question_type %>
        <%= f.select :question_type,
          options_for_select(Settings.question.types, @question.question_type),
          {}, {class: "form-control question-type"} %>
      </div>
      <% if @question.text? %>
        <%= f.fields_for :options do |answer| %>
          <div class="fields row">
            <p>
              <%= answer.hidden_field :_destroy %>
              <%= answer.label :content %>
              <div class="col-md-8">
                <%= answer.text_field :content, class: "form-control" %>
              </div>
            </p>
          </div>
        <% end %>
      <% else %>
        <%= f.fields_for :options do |option| %>
          <%= render partial: "option_fields", locals: {f: option} %>
        <% end %>
      <% end %>
      <div class="option-form row">
        <button class="add_fields btn btn-primary" name="options">
          <%= t "questions.add_option" %></button>
      </div>
      <div class="row">
        <%= f.submit t("questions.suggest"), class: "btn btn-primary" %>
      </div>
      <%= new_fields_template f, :options %>
    <% end %>
  </div>
</div>

app/views/admin/questions/index.html.erb
<div class="row">
  <div class="col-md-12 col-md-offset-0">
    <h2>
      <b><%= t "suggested_question" %></b>
      <%= link_to new_admin_question_path, class: "pull-right" do %>
        <span class="glyphicon glyphicon-plus"></span>
        <%= t "questions.new" %>
      <% end %>
    </h2>
    <%= render partial: "filter_question_options" %>
    <table class="table">
      <thead>
        <tr>
          <th class="number_id"><%= t "questions.stt" %></th>
          <th class="content"><%= t "questions.question" %></th>
          <th class="subject"><%= t "questions.subject" %></th>
          <th class="type"><%= t "questions.type" %></th>
          <th class="state"><%= t "questions.state" %></th>
          <th class="accept"></th>
          <th class="action"></th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each_with_index do |question, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to question.content, [:admin, question] %></td>
            <td><%= question.subject.name %></td>
            <td><%= question.question_type %></td>
            <td>
              <% if question.waitting? %>
                <span class="label label-warning"><%= question.status %></span>
              <% else %>
                <span class="label label-success"><%= question.status %></span>
              <% end %>
            </td>
            <td>
              <% if question.waitting? %>
                <%= link_to t("questions.accepted"), admin_question_path(question,
                  question: {status: "accepted"}), method: :patch,
                  class: "btn btn-primary" %>
              <% end %>
            </td>
            <td>
              <%= link_to t("delete"), [:admin, question], method: :delete,
              class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @questions %>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div id="question" class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t "questions.suggest_question" %></b></h2>
    <%= form_for [:admin, @question] do |f| %>
      <div class="row">
        <%= f.label :subject %>
        <%= f.select :subject_id,
          options_for_select(@subjects.collect{|subject| [subject.name, subject.id]},
          params[:subject_id]), {}, {class: "form-control"} %>
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
        <%= f.label :question_type %>
        <%= f.select :question_type,
          options_for_select(Settings.question.types, params[:question_type]),
          {}, {class: "form-control question-type"} %>
      </div>
      <div class="option-form row">
        <button class="add_fields btn btn-primary" name="options">
          <%= t "questions.add_option" %></button>
      </div>
      <div class="row">
        <%= f.submit t("questions.suggest"), class: "btn btn-primary" %>
      </div>
      <%= new_fields_template f, :options %>
    <% end %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2><b><%= t "questions.question" %></b></h2>
  <table class="table">
    <tbody>
      <tr>
        <td width="40%"><b><%= t "questions.content" %></b></td>
        <td><%= @question.content %></td>
      </tr>
      <tr>
        <td><b><%= t "questions.options" %></b></td>
        <td>
          <table>
            <tbody>
            <% unless @question.text? %>
              <% @question.options.each do |option| %>
                <tr>
                  <td>
                    <%= option.content %>
                  </td>
                  <td width="15%">
                    <% if option.is_correct %>
                      <span class="label label-primary"><%= t "questions.correct" %></span>
                    <% elsif %>
                      <span class="label label-danger"><%= t "questions.wrong" %></span>
                    <% end%>
                  </td>
                </tr>
              <% end %>
            <% else %>
              <tr>
                <% @question.options.each do |option| %>
                  <td><%= option.content %></td>
                <% end %>
              </tr>
            <% end %>
            </tbody>
          </table>
        </td>
      </tr>
      <tr>
        <td><b><%= t "questions.subject" %></b></td>
        <td><%= @question.subject.name %></td>
      </tr>
      <tr>
        <td><b><%= t "questions.type" %></b></td>
        <td><%= @question.question_type %></td>
      </tr>
      <tr>
        <td><b><%= t "questions.state" %></b></td>
        <td>
          <div class="state-label label label-warning">
            <%= @question.status %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <%= link_to t("edit"), [:admin, @question],
    class: "btn btn-primary glyphicon glyphicon-pencil btn-width" %>
  <%= link_to t("delete"), [:admin, @question], method: :delete,
    class: "btn btn-danger glyphicon glyphicon-trash btn-width" %>
</div>