config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  devise_for :users
  resources :users do
    resources :questions
  end
  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users
    resources :exams
  end
  resources :exams

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  resourcify
  TIME_PER_EXAM = 1200
  QUESTION_PER_EXAM = 10

  enum status: [:opened, :testing, :saved, :checking, :checked]

  has_many :sections
  has_many :questions, through: :sections
  belongs_to :user
  belongs_to :subject

  before_create :create_section
  after_update :send_email_result_exam
  after_create :send_email_delay_exam

  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :sections
  def time_per_exam
    Exam::TIME_PER_EXAM / 60
  end

  def time_remaining
    if self.opened? || self.testing? || self.saved?
      self.duration - Time.zone.now.to_i + self.started_at - self.spent_time
    end
  end

  def change_status_when_test
    if self.opened? ||self.saved?
      self.status = :testing
      self.started_at = Time.zone.now.to_i
      self.recalculate_time
      self.save
    end
  end

  def recalculate_time
    self.spent_time += Time.zone.now.to_i - self.started_at
  end

  def real_time_spent
    if self.testing?
      Exam::TIME_PER_EXAM - self.time_remaining
    else
      self.spent_time
    end
  end

  def send_email_result_exam
    HardWorker.perform_async self.id
  end

  def send_email_delay_exam
    ExamMailer.notify_delay(self).deliver_now
  end
  handle_asynchronously :send_email_delay_exam,
    run_at: Proc.new {8.hours.from_now}

  class << self
    def notify_when_end_of_month
      Exam.all.each do |exam|
        ExamMailer.notice_when_end_of_month(exam).deliver_now
      end
    end

    def statistic_exam
      self.sections.where(result: true).size
    end
  end

  private

  def create_section
    self.questions << self.subject.questions.order("RANDOM()")
      .limit(self.number_question)
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  load_and_authorize_resource
  def index
    @q = Exam.ransack params[:q]
    option = params[:option].nil? ? Settings.exam.filter.all : params[:option]
    @exams = @q.result.includes(:subject).send(option).page(params[:page])
      .per Settings.pagination.questions_per_page
  end

  def update
    @exam.status = :checked
    if @exam.update_attributes exam_params
      flash[:notice] = I18n.t "exam.checked"
      redirect_to admin_exams_path
     else
      flash[:alert] = I18n.t "exam.update_fail"
      render :edit
    end
  end

  def destroy
    @exam.destroy
    flash[:notice] = I18n.t "exam.destroyed"
    redirect_to admin_exams_path
  end

  private

  def exam_params
    params.require(:exam).permit :subject_id,
    sections_attributes: [:id, :result, answer: []]
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_resource
  def index
    @exam = Exam.new
    @subjects = Subject.all
    @exams = current_user.exams.page(params[:page]).per 20
  end

  def create
    @exam = Exam.new exam_params
    @exam.user_id = current_user.id
    if @exam.save
      flash[:notice] = I18n.t "exams.success"
      redirect_to exams_path
    else
      @subjects = Subject.all
      render :index
    end
  end

  def show
    @exam.change_status_when_test
  end

  def update
    @exam.recalculate_time
    @exam.status = :checking if params[:commit] == "finish"
    @exam.status= :saved if params[:commit] == "save"
    if @exam.update_attributes exam_params
      redirect_to exams_path
    else
      render :edit
    end
  end

  private

  def exam_params
    params.require(:exam).permit :subject_id,
      sections_attributes: [:id, :answer, answer: []]
  end
end

app/views/exams/_continue.html.haml
- if exam.opened? || exam.testing?
  = link_to t("exams.start"), exam_path(exam),
    class: "btn btn-success button exam"

- if exam.saved?
  = link_to t("exams.continue"), exam_path(exam),
    class: "btn btn-success button exam"

- if exam.checking?
  = link_to t("exams.view"), exam_path(exam),
    class: "btn btn-inverse button exam"

app/views/exams/_exam.html.haml
.col-md-12.col-md-offset-0
  = form_for @exam, html: {id: "submit-exam"} do |f|
    %ol
      = f.fields_for :sections do |section|
        = render "question", f: section
    .row
      .col-md-6.col-md-offset-3
        = f.submit :save, class: "btn btn-primary btn-submit"
        = f.submit :finish,
          class: "btn btn-danger btn-submit pull-right finish-exam"

app/views/exams/_exam_result.html.haml
.col-md-12.col-md-offset-0
  = form_for @exam do |f|
    %ol
      = f.fields_for :sections do |section|
        = render "question_result", f: section

app/views/exams/_question.html.haml
%li
  = f.object.question.content
%br
- if f.object.question.single?
  - f.object.question.options.each do |answer|
    = f.radio_button :answer, answer.id,
      {checked: f.object.answer.include?(answer.id.to_s), multiple: true}
    = answer.content
    %br
- if f.object.question.multiple?
  - f.object.question.options.each do |answer|
    = f.check_box :answer, {checked: f.object.answer.include?(answer.id.to_s),
      multiple: true}, answer.id, false
    = answer.content
    %br
- if f.object.question.text?
  = f.text_area :answer, class: "form-control",  size: "10x4",
    value: f.object.answer, placeholder: I18n.t("exams.enterAnswer")
  %br
%br

app/views/exams/_question_result.html.haml
%li
  = f.object.question.content
%br
  - if f.object.question.single?
    - f.object.question.options.each do |answer|
      - is_checked = f.object.answer.include?(answer.id.to_s)
      = f.radio_button :answer, answer.id,
        {checked: is_checked, multiple: true, disabled: true }
      - if is_checked && !answer.is_correct?
        %del
          = answer.content
        %br
      - else
        = answer.content
        %br
  - elsif f.object.question.multiple?
    - f.object.question.options.each do |answer|
      - is_checked = f.object.answer.include?(answer.id.to_s)
      = f.check_box :answer,
        {checked: is_checked, multiple: true, disabled: true},
        answer.id, false
      - if is_checked && !answer.is_correct?
        %del
          = answer.content
        %br
      - else
        = answer.content
        %br
  - elsif f.object.question.text?
    = f.text_area :answer, disabled: true, class: "form-control",
      size: "10x4", value: f.object.answer,
      placeholder: I18n.t("exams.enterAnswer")
    %br
%br

app/views/exams/_score.html.haml
- if exam.checked?

- else
  -

app/views/exams/_status.html.haml
- if exam.opened?
  %span.label.label-primary
    = exam.status

- if exam.testing?
  %span.label.label-warning
    = exam.status

- if exam.saved?
  %span.label.label-info
    = exam.status

- if exam.checking?
  %span.label.label-danger
    = exam.status

app/views/exams/index.html.haml
.col-md-12.col-md-offset-0
  .form-exam
    = form_for @exam, html: {class: "form-inline"} do |f|
      = f.collection_select :subject_id, @subjects, :id, :name, {},
        class: "form-control"
      = f.submit t("exams.create") , class: "btn btn-primary"
  %hr
  %table.table
    %thead
      %tr
        %th= t "exams.created_at"
        %th= t "exams.subject"
        %th= t "exams.status"
        %th= t "exams.duration"
        %th= t "exams.num_ques"
        %th= t "exams.spent_time"
        %th= t "exams.score"
        %th
    %tbody
      - @exams.each do |exam|
        %tr
          %td= I18n.l exam.created_at, format: :define
          %td= exam.subject.name
          %td= render partial: "status", locals: {exam: exam}
          %td= exam.time_per_exam
          %td= exam.number_question
          %td= exam.real_time_spent
          %td= render partial: "score", locals: {exam: exam}
          %td= render partial: "continue", locals: {exam: exam}
  .text-center
    = paginate @exams

app/views/exams/show.html.haml
.col-md-8.col-md-offset-1
  %h1.text-center= @exam.subject.name
  %hr
  = render (@exam.testing? || @exam.saved?) ? "exam" : "exam_result"

.col-md-2
  %span#cdtime{"data-duration"=> "#{@exam.time_remaining}",
    "data-redirect"=> "#{url_for controller: "exams", action: "index"}",
    "data-msgout"=> "#{t "exams.timeout"}" }