config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  devise_for :users
  resources :users do
    resources :questions
  end
  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users
    resources :exams
  end
  resources :exams

end

app/views/layouts/_footer.html.haml
.container
  %small
    The
    %a{ :href => "#"}FTS_46
    by
    %a{ :href => "#"}Anh Tuan, Duy Dat

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse
  %div.col-md-3.col-md-offset-1
    %ul.nav.navbar-nav
      %li
        = link_to image_tag( 'logo.png'),'/'
  %div.col-md-8.col-md-offset-0
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to t("home"), root_path
        - if user_signed_in?
          = render "layouts/menu"
        - else
          %li
            = link_to t("login"), new_user_session_path

app/views/layouts/_menu.html.haml
- if can? :manage, :all
  %li
    = link_to t("exams.manage_users"), admin_users_path
  %li
    = link_to t("exams.manage_exams"), admin_exams_path
  %li
    = link_to t("exams.manage_subjects"), admin_subjects_path
  %li
    = link_to t("exams.manage_questions"), admin_questions_path

- if cannot? :manage, :all
  %li
    = link_to t("exams.exam"), exams_path
  %li
    = link_to t("questions.new"), user_questions_path(current_user)

%li.dropdown
  %a.dropdown-toggle{"href"=>"#","data-toggle"=>"dropdown"}
    = t "account"
    %b.caret
  %ul.dropdown-menu
    %li
      = link_to t("profile"), edit_user_registration_path
    %li.divider
    %li
      = link_to t("logout"), destroy_user_session_path, method: "delete"

app/views/layouts/_message.html.haml
- if notice
  %p.alert.alert-success
    = notice

- if alert
  %p.alert.alert-danger
    = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8",
      "http-equiv" => "Content-Type"}
    %title fts_46
    = stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true
    = javascript_include_tag "application", "data-turbolinks-track": true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container
      = render "layouts/message"
      = yield
    = render "layouts/footer"